apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: reverseproxy
